### ISSUE TITLE
Suggestion for improvement in Getting Started

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/vulcan-next-starter#8]
Hi,

I suggest for improvement in Getting Started as following:

In another terminal, run the Next development server:

GRAPHQL_URL="your-vulcan-server-url" npm run dev
&#35;or
GRAPHQL_URL="your-vulcan-server-url" yarn dev

Should change to =>

In another terminal, run the Next development server:
git clone https://github.com/VulcanJS/vulcan-next-starter.git
cd vulcan-next-starter
npm install next react react-dom
yarn add @apollo/react-hooks apollo-cache-inmemory apollo-client apollo-link-http apollo-link-ws graphql graphql-tag subscriptions-transport-ws isomorphic-unfetch next-with-apollo
yarn add typescript -D

GRAPHQL_URL="your-vulcan-server-url" npm run dev
&#35;or
GRAPHQL_URL="your-vulcan-server-url" yarn dev

Thank You
Adalidda

**Comment by eric-burel** [comment]
Hi, can you please clarify the change? Note that this repo is under development, its not yet really meant to be used

**Comment by adalidda** [comment]
Hi @eric-burel 

I mean that the Getting Started should provide more information on how to git clone and install the package need to make it working (next js, react, typescript) that why I propose to add

git clone https://github.com/VulcanJS/vulcan-next-starter.git
cd vulcan-next-starter
npm install next react react-dom
yarn add @apollo/react-hooks apollo-cache-inmemory apollo-client apollo-link-http apollo-link-ws graphql graphql-tag subscriptions-transport-ws isomorphic-unfetch next-with-apollo
yarn add typescript -D

Thank You
Adalidda

**Comment by eric-burel** [comment]
Ok got it, it's just that it is unfinished yet it will improve with the incoming developments
